In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
# importar el archivo csv AccidentesBicicletas_2022.csv

df = pd.read_csv('AccidentesBicicletas_2022.csv', sep=';', encoding='latin-1')

df.head()

,ï»¿num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorolÃ³gico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022S000034,02/01/2022,0:05:00,"CALL. MARIA TERESA SAENZ DE HEREDIA, 6",6,15,CIUDAD LINEAL,CaÃ­da,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 aÃ±os,Hombre,7.0,Asistencia sanitaria sÃ³lo en el lugar del acc...,444.462.918,4.474.808.752,S,NaN
1,2022S000290,05/01/2022,10:45:00,PASEO. MARQUES DE MONISTROL / GTA. PUENTE DE S...,1,10,LATINA,ColisiÃ³n fronto-lateral,Se desconoce,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 aÃ±os,Mujer,7.0,Asistencia sanitaria sÃ³lo en el lugar del acc...,438.584.377,4.473.973.210,N,NaN
2,2022S000292,07/01/2022,13:55:00,"CALL. PICO CLAVERO, 4A",4A,13,PUENTE DE VALLECAS,CaÃ­da,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 60 a 64 aÃ±os,Mujer,6.0,Asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,N,NaN
3,2022S000340,08/01/2022,3:00:00,"CALL. HUERTAS, 24",24,1,CENTRO,CaÃ­da,Despejado,Bicicleta,Conductor,De 30 a 34 aÃ±os,Mujer,1.0,AtenciÃ³n en urgencias sin posterior ingreso,440.663.453,4.473.911.843,N,NaN
4,2022S000359,07/01/2022,18:40:00,PQUE. FUENTE CARRANTONA / AUTOV. M-23,0,14,MORATALAZ,CaÃ­da,Despejado,Bicicleta,Conductor,De 55 a 59 aÃ±os,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,N,NaN

In [51]:
df.shape

(878, 19)

In [52]:
# descomprimir el archivo zip

import zipfile

with zipfile.ZipFile('trips_22_01_January-csv.zip', 'r') as zip_ref:
    zip_ref.extractall('trips_22_01_January-csv')

# importar el archivo csv trips_22_01_January-csv

df2 = pd.read_csv('trips_22_01_January-csv/trips_22_01_January.csv', sep=';', encoding='latin-1')

df2.shape

(489520, 19)

In [53]:
# comprobar los archivos duplicados

df2.duplicated().sum()

244759

In [54]:
# eliminar los archivos duplicados

df2.drop_duplicates(inplace=True)

df2.shape

(244761, 19)

In [55]:
# comprobar los archivos con nulos

df2.isnull().sum()

fecha                       1
idTrip                      1
idBike                      1
fleet                       1
trip_minutes                1
geolocation_unlock          1
address_unlock         242783
unlock_date                 1
locktype                    1
unlocktype                  1
geolocation_lock            1
address_lock           242345
lock_date                   1
station_unlock           1871
dock_unlock              1871
unlock_station_name      1871
station_lock             2308
dock_lock                2308
lock_station_name        2308
dtype: int64

In [57]:
df2.head()

,fecha,idTrip,idBike,fleet,trip_minutes,geolocation_unlock,address_unlock,unlock_date,locktype,unlocktype,geolocation_lock,address_lock,lock_date,station_unlock,dock_unlock,unlock_station_name,station_lock,dock_lock,lock_station_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,489978239_1718_2022-01-01T00:18:37,1718.0,1.0,16.28,"{'type': 'Point', 'coordinates': [-3.6714166, ...",NaN,2022-01-01T00:02:20,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688398, 4...",NaN,2022-01-01T00:18:37,200.0,3.0,Avenida de los Toreros,64.0,4.0,Plaza de la Independencia
3,2022-01-01,06023769T_7340_2022-01-01T00:14:59,7340.0,1.0,7.10,"{'type': 'Point', 'coordinates': [-3.6894193, ...",NaN,2022-01-01T00:07:53,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6993465, ...",NaN,2022-01-01T00:14:59,69.0,5.0,Antonio Maura,169.0,17.0,Manuel Silvela
5,2022-01-01,50856526F_3861_2022-01-01T00:09:50,3861.0,1.0,0.48,"{'type': 'Point', 'coordinates': [-3.688822, 4...",NaN,2022-01-01T00:09:21,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688822, 4...",NaN,2022-01-01T00:09:50,73.0,21.0,Puerta del Ãngel CaÃ­do,73.0,21.0,Puerta del Ãngel CaÃ­do
7,2022-01-01,79006741Q_7657_2022-01-01T00:16:29,7657.0,1.0,6.62,"{'type': 'Point', 'coordinates': [-3.6653055, ...",NaN,2022-01-01T00:09:52,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6657777, ...",NaN,2022-01-01T00:16:29,192.0,22.0,MarquÃ©s de Zafra,190.0,17.0,Parque Roma

In [56]:
# eliminar todas las filas con nulos

#df2.dropna(inplace=True)

#df2.shape