In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [97]:
# importar el archivo csv AccidentesBicicletas_2022.csv

df = pd.read_csv('AccidentesBicicletas_2022.csv', sep=';', encoding='latin-1')

df.head()

,ï»¿num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorolÃ³gico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022S000034,02/01/2022,0:05:00,"CALL. MARIA TERESA SAENZ DE HEREDIA, 6",6,15,CIUDAD LINEAL,CaÃ­da,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 aÃ±os,Hombre,7.0,Asistencia sanitaria sÃ³lo en el lugar del acc...,444.462.918,4.474.808.752,S,NaN
1,2022S000290,05/01/2022,10:45:00,PASEO. MARQUES DE MONISTROL / GTA. PUENTE DE S...,1,10,LATINA,ColisiÃ³n fronto-lateral,Se desconoce,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 aÃ±os,Mujer,7.0,Asistencia sanitaria sÃ³lo en el lugar del acc...,438.584.377,4.473.973.210,N,NaN
2,2022S000292,07/01/2022,13:55:00,"CALL. PICO CLAVERO, 4A",4A,13,PUENTE DE VALLECAS,CaÃ­da,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 60 a 64 aÃ±os,Mujer,6.0,Asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,N,NaN
3,2022S000340,08/01/2022,3:00:00,"CALL. HUERTAS, 24",24,1,CENTRO,CaÃ­da,Despejado,Bicicleta,Conductor,De 30 a 34 aÃ±os,Mujer,1.0,AtenciÃ³n en urgencias sin posterior ingreso,440.663.453,4.473.911.843,N,NaN
4,2022S000359,07/01/2022,18:40:00,PQUE. FUENTE CARRANTONA / AUTOV. M-23,0,14,MORATALAZ,CaÃ­da,Despejado,Bicicleta,Conductor,De 55 a 59 aÃ±os,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,N,NaN

In [98]:
df.shape

(878, 19)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ï»¿num_expediente      878 non-null    object
 1   fecha                  878 non-null    object
 2   hora                   878 non-null    object
 3   localizacion           878 non-null    object
 4   numero                 878 non-null    object
 5   cod_distrito           878 non-null    int64
 6   distrito               878 non-null    object
 7   tipo_accidente         878 non-null    object
 8   estado_meteorolÃ³gico  853 non-null    object
 9   tipo_vehiculo          878 non-null    object
 10  tipo_persona           878 non-null    object
 11  rango_edad             878 non-null    object
 12  sexo                   878 non-null    object
 13  cod_lesividad          749 non-null    float64
 14  lesividad              749 non-null    object
 15  coordenada_x_utm       878 non-null    object
 16  coordenada_y_utm       878 non-null    object
 17  positiva_alcohol       877 non-null    object
 18  positiva_droga         0 non-null      float64
dtypes: float64(2), int64(1), object(16)
memory usage: 130.5+ KB

In [100]:
import pandas as pd

def replace_multiple(df, column, replacements):
    # Verificar si la columna es de tipo cadena (string)
    if df[column].dtype == 'O':
        for old, new in replacements.items():
            df[column] = df[column].str.replace(old, new)
    else:
        print(f"La columna {column} no es de tipo cadena (string) y no se realizaron cambios.")

    return df[column]

# Ejemplo de uso:
# Supongamos que df es tu DataFrame original

# Definir los reemplazos deseados
replacements = {
    'Ã': 'Á',
    'Ã‰': 'É',
    'Ã': 'Í',
    'Ã“': 'Ó',
    'Ãš': 'Ú',
    'Ã‘': 'Ñ',
    'Ã¡': 'á',
    'Ã©': 'é',
    'Ã­': 'í',
    'Ã³': 'ó',
    'Ãº': 'ú',
    'Ã±': 'ñ'
}

In [101]:
#hacer una lista de las columnas que tengan valores de tipo object

df.select_dtypes(include=['object']).columns

# aplivar la función de reemplazo para las columnas que tengan valores de tipo object

for col in df.select_dtypes(include=['object']).columns:
    df[col] = replace_multiple(df, col, replacements)

df.head()

,ï»¿num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorolÃ³gico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022S000034,02/01/2022,0:05:00,"CALL. MARIA TERESA SAENZ DE HEREDIA, 6",6,15,CIUDAD LINEAL,Caída,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 años,Hombre,7.0,Asistencia sanitaria sólo en el lugar del acci...,444.462.918,4.474.808.752,S,NaN
1,2022S000290,05/01/2022,10:45:00,PASEO. MARQUES DE MONISTROL / GTA. PUENTE DE S...,1,10,LATINA,Colisión fronto-lateral,Se desconoce,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 años,Mujer,7.0,Asistencia sanitaria sólo en el lugar del acci...,438.584.377,4.473.973.210,N,NaN
2,2022S000292,07/01/2022,13:55:00,"CALL. PICO CLAVERO, 4A",4A,13,PUENTE DE VALLECAS,Caída,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 60 a 64 años,Mujer,6.0,Asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,N,NaN
3,2022S000340,08/01/2022,3:00:00,"CALL. HUERTAS, 24",24,1,CENTRO,Caída,Despejado,Bicicleta,Conductor,De 30 a 34 años,Mujer,1.0,Atención en urgencias sin posterior ingreso,440.663.453,4.473.911.843,N,NaN
4,2022S000359,07/01/2022,18:40:00,PQUE. FUENTE CARRANTONA / AUTOV. M-23,0,14,MORATALAZ,Caída,Despejado,Bicicleta,Conductor,De 55 a 59 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,N,NaN

In [102]:
# hacer una funcion que convierta todos los strings a minusculas del dataframe

def minusculas(df):
    for i in df:
        if df[i].dtype == 'object':
            df[i] = df[i].str.lower()
    return df

minusculas(df)

df.head()

,ï»¿num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorolÃ³gico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022s000034,02/01/2022,0:05:00,"call. maria teresa saenz de heredia, 6",6,15,ciudad lineal,caída,despejado,bicicleta epac (pedaleo asistido),conductor,de 25 a 29 años,hombre,7.0,asistencia sanitaria sólo en el lugar del acci...,444.462.918,4.474.808.752,s,NaN
1,2022s000290,05/01/2022,10:45:00,paseo. marques de monistrol / gta. puente de s...,1,10,latina,colisión fronto-lateral,se desconoce,bicicleta epac (pedaleo asistido),conductor,de 25 a 29 años,mujer,7.0,asistencia sanitaria sólo en el lugar del acci...,438.584.377,4.473.973.210,n,NaN
2,2022s000292,07/01/2022,13:55:00,"call. pico clavero, 4a",4a,13,puente de vallecas,caída,despejado,bicicleta epac (pedaleo asistido),conductor,de 60 a 64 años,mujer,6.0,asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,n,NaN
3,2022s000340,08/01/2022,3:00:00,"call. huertas, 24",24,1,centro,caída,despejado,bicicleta,conductor,de 30 a 34 años,mujer,1.0,atención en urgencias sin posterior ingreso,440.663.453,4.473.911.843,n,NaN
4,2022s000359,07/01/2022,18:40:00,pque. fuente carrantona / autov. m-23,0,14,moratalaz,caída,despejado,bicicleta,conductor,de 55 a 59 años,hombre,6.0,asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,n,NaN

In [ ]:
# descomprimir el archivo zip

import zipfile

with zipfile.ZipFile('trips_22_01_January-csv.zip', 'r') as zip_ref:
    zip_ref.extractall('trips_22_01_January-csv')

# importar el archivo csv trips_22_01_January-csv

df2 = pd.read_csv('trips_22_01_January-csv/trips_22_01_January.csv', sep=';', encoding='latin-1')

df2.shape

(489520, 19)

In [ ]:
# comprobar los archivos duplicados

df2.duplicated().sum()

244759

In [ ]:
# eliminar los archivos duplicados

df2.drop_duplicates(inplace=True)

df2.shape

(244761, 19)

In [ ]:
# comprobar los archivos con nulos

df2.isnull().sum()

fecha                       1
idTrip                      1
idBike                      1
fleet                       1
trip_minutes                1
geolocation_unlock          1
address_unlock         242783
unlock_date                 1
locktype                    1
unlocktype                  1
geolocation_lock            1
address_lock           242345
lock_date                   1
station_unlock           1871
dock_unlock              1871
unlock_station_name      1871
station_lock             2308
dock_lock                2308
lock_station_name        2308
dtype: int64

In [ ]:
df2.head()

,fecha,idTrip,idBike,fleet,trip_minutes,geolocation_unlock,address_unlock,unlock_date,locktype,unlocktype,geolocation_lock,address_lock,lock_date,station_unlock,dock_unlock,unlock_station_name,station_lock,dock_lock,lock_station_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,489978239_1718_2022-01-01T00:18:37,1718.0,1.0,16.28,"{'type': 'Point', 'coordinates': [-3.6714166, ...",NaN,2022-01-01T00:02:20,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688398, 4...",NaN,2022-01-01T00:18:37,200.0,3.0,Avenida de los Toreros,64.0,4.0,Plaza de la Independencia
3,2022-01-01,06023769T_7340_2022-01-01T00:14:59,7340.0,1.0,7.10,"{'type': 'Point', 'coordinates': [-3.6894193, ...",NaN,2022-01-01T00:07:53,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6993465, ...",NaN,2022-01-01T00:14:59,69.0,5.0,Antonio Maura,169.0,17.0,Manuel Silvela
5,2022-01-01,50856526F_3861_2022-01-01T00:09:50,3861.0,1.0,0.48,"{'type': 'Point', 'coordinates': [-3.688822, 4...",NaN,2022-01-01T00:09:21,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688822, 4...",NaN,2022-01-01T00:09:50,73.0,21.0,Puerta del Ãngel CaÃ­do,73.0,21.0,Puerta del Ãngel CaÃ­do
7,2022-01-01,79006741Q_7657_2022-01-01T00:16:29,7657.0,1.0,6.62,"{'type': 'Point', 'coordinates': [-3.6653055, ...",NaN,2022-01-01T00:09:52,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6657777, ...",NaN,2022-01-01T00:16:29,192.0,22.0,MarquÃ©s de Zafra,190.0,17.0,Parque Roma

In [ ]:
# eliminar todas las filas con nulos

#df2.dropna(inplace=True)

#df2.shape