In [168]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [169]:
# importar el archivo csv AccidentesBicicletas_2022.csv

accidentes = pd.read_csv('AccidentesBicicletas_2022.csv', sep=';', encoding='latin-1')

accidentes.head()

,ï»¿num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorolÃ³gico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022S000034,02/01/2022,0:05:00,"CALL. MARIA TERESA SAENZ DE HEREDIA, 6",6,15,CIUDAD LINEAL,CaÃ­da,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 aÃ±os,Hombre,7.0,Asistencia sanitaria sÃ³lo en el lugar del acc...,444.462.918,4.474.808.752,S,NaN
1,2022S000290,05/01/2022,10:45:00,PASEO. MARQUES DE MONISTROL / GTA. PUENTE DE S...,1,10,LATINA,ColisiÃ³n fronto-lateral,Se desconoce,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 aÃ±os,Mujer,7.0,Asistencia sanitaria sÃ³lo en el lugar del acc...,438.584.377,4.473.973.210,N,NaN
2,2022S000292,07/01/2022,13:55:00,"CALL. PICO CLAVERO, 4A",4A,13,PUENTE DE VALLECAS,CaÃ­da,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 60 a 64 aÃ±os,Mujer,6.0,Asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,N,NaN
3,2022S000340,08/01/2022,3:00:00,"CALL. HUERTAS, 24",24,1,CENTRO,CaÃ­da,Despejado,Bicicleta,Conductor,De 30 a 34 aÃ±os,Mujer,1.0,AtenciÃ³n en urgencias sin posterior ingreso,440.663.453,4.473.911.843,N,NaN
4,2022S000359,07/01/2022,18:40:00,PQUE. FUENTE CARRANTONA / AUTOV. M-23,0,14,MORATALAZ,CaÃ­da,Despejado,Bicicleta,Conductor,De 55 a 59 aÃ±os,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,N,NaN

In [170]:
accidentes.shape

(878, 19)

In [171]:
accidentes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ï»¿num_expediente      878 non-null    object
 1   fecha                  878 non-null    object
 2   hora                   878 non-null    object
 3   localizacion           878 non-null    object
 4   numero                 878 non-null    object
 5   cod_distrito           878 non-null    int64
 6   distrito               878 non-null    object
 7   tipo_accidente         878 non-null    object
 8   estado_meteorolÃ³gico  853 non-null    object
 9   tipo_vehiculo          878 non-null    object
 10  tipo_persona           878 non-null    object
 11  rango_edad             878 non-null    object
 12  sexo                   878 non-null    object
 13  cod_lesividad          749 non-null    float64
 14  lesividad              749 non-null    object
 15  coordenada_x_utm       878 non-null    object
 16  coordenada_y_utm       878 non-null    object
 17  positiva_alcohol       877 non-null    object
 18  positiva_droga         0 non-null      float64
dtypes: float64(2), int64(1), object(16)
memory usage: 130.5+ KB

In [172]:
import pandas as pd

def replace_multiple(df, column, replacements):
    # Verificar si la columna es de tipo cadena (string)
    if df[column].dtype == 'O':
        for old, new in replacements.items():
            df[column] = df[column].str.replace(old, new)
    else:
        print(f"La columna {column} no es de tipo cadena (string) y no se realizaron cambios.")

    return df[column]

# Ejemplo de uso:
# Supongamos que df es tu DataFrame original

# Definir los reemplazos deseados
replacements = {
    'Ã': 'A',
    'Ã‰': 'E',
    'Ã': 'I',
    'Ã“': 'O',
    'Ãš': 'U',
    'Ã‘': 'Ñ',
    'Ã¡': 'a',
    'Ã©': 'e',
    'Ã­': 'i',
    'Ã³': 'o',
    'Ãº': 'u',
    'Ã±': 'ñ'
}

In [173]:
#hacer una lista de las columnas que tengan valores de tipo object

accidentes.select_dtypes(include=['object']).columns

# aplivar la función de reemplazo para las columnas que tengan valores de tipo object

for col in accidentes.select_dtypes(include=['object']).columns:
    accidentes[col] = replace_multiple(accidentes, col, replacements)

accidentes.head()

,ï»¿num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorolÃ³gico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022S000034,02/01/2022,0:05:00,"CALL. MARIA TERESA SAENZ DE HEREDIA, 6",6,15,CIUDAD LINEAL,Caida,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 años,Hombre,7.0,Asistencia sanitaria solo en el lugar del acci...,444.462.918,4.474.808.752,S,NaN
1,2022S000290,05/01/2022,10:45:00,PASEO. MARQUES DE MONISTROL / GTA. PUENTE DE S...,1,10,LATINA,Colision fronto-lateral,Se desconoce,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 años,Mujer,7.0,Asistencia sanitaria solo en el lugar del acci...,438.584.377,4.473.973.210,N,NaN
2,2022S000292,07/01/2022,13:55:00,"CALL. PICO CLAVERO, 4A",4A,13,PUENTE DE VALLECAS,Caida,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 60 a 64 años,Mujer,6.0,Asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,N,NaN
3,2022S000340,08/01/2022,3:00:00,"CALL. HUERTAS, 24",24,1,CENTRO,Caida,Despejado,Bicicleta,Conductor,De 30 a 34 años,Mujer,1.0,Atencion en urgencias sin posterior ingreso,440.663.453,4.473.911.843,N,NaN
4,2022S000359,07/01/2022,18:40:00,PQUE. FUENTE CARRANTONA / AUTOV. M-23,0,14,MORATALAZ,Caida,Despejado,Bicicleta,Conductor,De 55 a 59 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,N,NaN

In [174]:
# cambiar los nombres de las columnas "	ï»¿num_expediente" y "estado_meteorolÃ³gico" por "num_expediente" y "estado_meteorologico"

accidentes.rename(columns={'ï»¿num_expediente':'num_expediente', 'estado_meteorolÃ³gico':'estado_meteorologico'}, inplace=True)

accidentes.head()

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorologico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022S000034,02/01/2022,0:05:00,"CALL. MARIA TERESA SAENZ DE HEREDIA, 6",6,15,CIUDAD LINEAL,Caida,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 años,Hombre,7.0,Asistencia sanitaria solo en el lugar del acci...,444.462.918,4.474.808.752,S,NaN
1,2022S000290,05/01/2022,10:45:00,PASEO. MARQUES DE MONISTROL / GTA. PUENTE DE S...,1,10,LATINA,Colision fronto-lateral,Se desconoce,Bicicleta EPAC (pedaleo asistido),Conductor,De 25 a 29 años,Mujer,7.0,Asistencia sanitaria solo en el lugar del acci...,438.584.377,4.473.973.210,N,NaN
2,2022S000292,07/01/2022,13:55:00,"CALL. PICO CLAVERO, 4A",4A,13,PUENTE DE VALLECAS,Caida,Despejado,Bicicleta EPAC (pedaleo asistido),Conductor,De 60 a 64 años,Mujer,6.0,Asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,N,NaN
3,2022S000340,08/01/2022,3:00:00,"CALL. HUERTAS, 24",24,1,CENTRO,Caida,Despejado,Bicicleta,Conductor,De 30 a 34 años,Mujer,1.0,Atencion en urgencias sin posterior ingreso,440.663.453,4.473.911.843,N,NaN
4,2022S000359,07/01/2022,18:40:00,PQUE. FUENTE CARRANTONA / AUTOV. M-23,0,14,MORATALAZ,Caida,Despejado,Bicicleta,Conductor,De 55 a 59 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,N,NaN

In [175]:
# hacer una funcion que convierta todos los strings a minusculas del dataframe

def minusculas(df):
    for i in df:
        if df[i].dtype == 'object':
            df[i] = df[i].str.lower()
    return df

minusculas(accidentes)

accidentes.head()

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorologico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2022s000034,02/01/2022,0:05:00,"call. maria teresa saenz de heredia, 6",6,15,ciudad lineal,caida,despejado,bicicleta epac (pedaleo asistido),conductor,de 25 a 29 años,hombre,7.0,asistencia sanitaria solo en el lugar del acci...,444.462.918,4.474.808.752,s,NaN
1,2022s000290,05/01/2022,10:45:00,paseo. marques de monistrol / gta. puente de s...,1,10,latina,colision fronto-lateral,se desconoce,bicicleta epac (pedaleo asistido),conductor,de 25 a 29 años,mujer,7.0,asistencia sanitaria solo en el lugar del acci...,438.584.377,4.473.973.210,n,NaN
2,2022s000292,07/01/2022,13:55:00,"call. pico clavero, 4a",4a,13,puente de vallecas,caida,despejado,bicicleta epac (pedaleo asistido),conductor,de 60 a 64 años,mujer,6.0,asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,n,NaN
3,2022s000340,08/01/2022,3:00:00,"call. huertas, 24",24,1,centro,caida,despejado,bicicleta,conductor,de 30 a 34 años,mujer,1.0,atencion en urgencias sin posterior ingreso,440.663.453,4.473.911.843,n,NaN
4,2022s000359,07/01/2022,18:40:00,pque. fuente carrantona / autov. m-23,0,14,moratalaz,caida,despejado,bicicleta,conductor,de 55 a 59 años,hombre,6.0,asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,n,NaN

In [176]:
# eliminamos la columna positiva_droga por que tiene muchos valores nulos

accidentes.drop('positiva_droga', axis=1, inplace=True)

accidentes.head()

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorologico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol
0,2022s000034,02/01/2022,0:05:00,"call. maria teresa saenz de heredia, 6",6,15,ciudad lineal,caida,despejado,bicicleta epac (pedaleo asistido),conductor,de 25 a 29 años,hombre,7.0,asistencia sanitaria solo en el lugar del acci...,444.462.918,4.474.808.752,s
1,2022s000290,05/01/2022,10:45:00,paseo. marques de monistrol / gta. puente de s...,1,10,latina,colision fronto-lateral,se desconoce,bicicleta epac (pedaleo asistido),conductor,de 25 a 29 años,mujer,7.0,asistencia sanitaria solo en el lugar del acci...,438.584.377,4.473.973.210,n
2,2022s000292,07/01/2022,13:55:00,"call. pico clavero, 4a",4a,13,puente de vallecas,caida,despejado,bicicleta epac (pedaleo asistido),conductor,de 60 a 64 años,mujer,6.0,asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,n
3,2022s000340,08/01/2022,3:00:00,"call. huertas, 24",24,1,centro,caida,despejado,bicicleta,conductor,de 30 a 34 años,mujer,1.0,atencion en urgencias sin posterior ingreso,440.663.453,4.473.911.843,n
4,2022s000359,07/01/2022,18:40:00,pque. fuente carrantona / autov. m-23,0,14,moratalaz,caida,despejado,bicicleta,conductor,de 55 a 59 años,hombre,6.0,asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,n

In [177]:
# contamos los valores de la columna rango_edad

accidentes.rango_edad.value_counts()

de 25 a 29 años    119
de 30 a 34 años    106
de 50 a 54 años     74
de 55 a 59 años     74
de 45 a 49 años     74
de 35 a 39 años     73
de 21 a 24 años     73
de 40 a 44 años     72
de 18 a 20 años     46
de 60 a 64 años     42
de 10 a 14 años     23
de 15 a 17 años     21
de 65 a 69 años     20
de 70 a 74 años     17
mas de 74 años      16
desconocido         15
de 6 a 9 años        7
menor de 5 años      6
Name: rango_edad, dtype: int64

In [178]:
def mapear_rango_edad(df):
    mapeo_edad = {
        'menor de 5 años': 'niño',
        'de 6 a 9 años': 'niño',
        'de 10 a 14 años': 'niño',
        'de 15 a 17 años': 'adolescente',
        'de 18 a 20 años': 'joven',
        'de 21 a 24 años': 'joven',
        'de 25 a 29 años': 'joven',
        'de 30 a 34 años': 'adulto',
        'de 35 a 39 años': 'adulto',
        'de 40 a 44 años': 'adulto',
        'de 45 a 49 años': 'adulto',
        'de 50 a 54 años': 'adulto',
        'de 55 a 59 años': 'adulto',
        'de 60 a 64 años': 'adulto',
        'de 65 a 69 años': 'mayor',
        'de 70 a 74 años': 'mayor',
        'más de 74 años': 'mayor'
    }

    df.rango_edad = df.rango_edad.replace(mapeo_edad)
    return df

# Llamada a la función
df = mapear_rango_edad(accidentes)

accidentes.rango_edad.value_counts()

adulto            515
joven             238
mayor              37
niño               36
adolescente        21
mas de 74 años     16
desconocido        15
Name: rango_edad, dtype: int64

In [179]:
# rellenamos los missing values del dataframe con la moda de cada columna

accidentes.fillna(df.mode().iloc[0], inplace=True)

accidentes.head()

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorologico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol
0,2022s000034,02/01/2022,0:05:00,"call. maria teresa saenz de heredia, 6",6,15,ciudad lineal,caida,despejado,bicicleta epac (pedaleo asistido),conductor,joven,hombre,7.0,asistencia sanitaria solo en el lugar del acci...,444.462.918,4.474.808.752,s
1,2022s000290,05/01/2022,10:45:00,paseo. marques de monistrol / gta. puente de s...,1,10,latina,colision fronto-lateral,se desconoce,bicicleta epac (pedaleo asistido),conductor,joven,mujer,7.0,asistencia sanitaria solo en el lugar del acci...,438.584.377,4.473.973.210,n
2,2022s000292,07/01/2022,13:55:00,"call. pico clavero, 4a",4a,13,puente de vallecas,caida,despejado,bicicleta epac (pedaleo asistido),conductor,adulto,mujer,6.0,asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,n
3,2022s000340,08/01/2022,3:00:00,"call. huertas, 24",24,1,centro,caida,despejado,bicicleta,conductor,adulto,mujer,1.0,atencion en urgencias sin posterior ingreso,440.663.453,4.473.911.843,n
4,2022s000359,07/01/2022,18:40:00,pque. fuente carrantona / autov. m-23,0,14,moratalaz,caida,despejado,bicicleta,conductor,adulto,hombre,6.0,asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,n

In [180]:
# eliminamos los elemnetos de la columna de localizacion que esten a partir de la coma

accidentes['localizacion'] = accidentes['localizacion'].str.split(',').str[0]

accidentes.head()

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorologico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol
0,2022s000034,02/01/2022,0:05:00,call. maria teresa saenz de heredia,6,15,ciudad lineal,caida,despejado,bicicleta epac (pedaleo asistido),conductor,joven,hombre,7.0,asistencia sanitaria solo en el lugar del acci...,444.462.918,4.474.808.752,s
1,2022s000290,05/01/2022,10:45:00,paseo. marques de monistrol / gta. puente de s...,1,10,latina,colision fronto-lateral,se desconoce,bicicleta epac (pedaleo asistido),conductor,joven,mujer,7.0,asistencia sanitaria solo en el lugar del acci...,438.584.377,4.473.973.210,n
2,2022s000292,07/01/2022,13:55:00,call. pico clavero,4a,13,puente de vallecas,caida,despejado,bicicleta epac (pedaleo asistido),conductor,adulto,mujer,6.0,asistencia sanitaria inmediata en centro de sa...,443.492.680,4.472.691.807,n
3,2022s000340,08/01/2022,3:00:00,call. huertas,24,1,centro,caida,despejado,bicicleta,conductor,adulto,mujer,1.0,atencion en urgencias sin posterior ingreso,440.663.453,4.473.911.843,n
4,2022s000359,07/01/2022,18:40:00,pque. fuente carrantona / autov. m-23,0,14,moratalaz,caida,despejado,bicicleta,conductor,adulto,hombre,6.0,asistencia sanitaria inmediata en centro de sa...,446.645.011,4.473.884.612,n

In [181]:
# descomprimir el archivo zip

import zipfile

with zipfile.ZipFile('trips_22_01_January-csv.zip', 'r') as zip_ref:
    zip_ref.extractall('trips_22_01_January-csv')

# importar el archivo csv trips_22_01_January-csv

enero = pd.read_csv('trips_22_01_January-csv/trips_22_01_January.csv', sep=';', encoding='latin-1')

enero.shape

(489520, 19)

In [182]:
# comprobar los archivos duplicados

enero.duplicated().sum()

244759

In [183]:
# eliminar los archivos duplicados

enero.drop_duplicates(inplace=True)

enero.shape

(244761, 19)

In [184]:
# comprobar los archivos con nulos

enero.isnull().sum()

fecha                       1
idTrip                      1
idBike                      1
fleet                       1
trip_minutes                1
geolocation_unlock          1
address_unlock         242783
unlock_date                 1
locktype                    1
unlocktype                  1
geolocation_lock            1
address_lock           242345
lock_date                   1
station_unlock           1871
dock_unlock              1871
unlock_station_name      1871
station_lock             2308
dock_lock                2308
lock_station_name        2308
dtype: int64

In [185]:
enero.head()

,fecha,idTrip,idBike,fleet,trip_minutes,geolocation_unlock,address_unlock,unlock_date,locktype,unlocktype,geolocation_lock,address_lock,lock_date,station_unlock,dock_unlock,unlock_station_name,station_lock,dock_lock,lock_station_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,489978239_1718_2022-01-01T00:18:37,1718.0,1.0,16.28,"{'type': 'Point', 'coordinates': [-3.6714166, ...",NaN,2022-01-01T00:02:20,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688398, 4...",NaN,2022-01-01T00:18:37,200.0,3.0,Avenida de los Toreros,64.0,4.0,Plaza de la Independencia
3,2022-01-01,06023769T_7340_2022-01-01T00:14:59,7340.0,1.0,7.10,"{'type': 'Point', 'coordinates': [-3.6894193, ...",NaN,2022-01-01T00:07:53,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6993465, ...",NaN,2022-01-01T00:14:59,69.0,5.0,Antonio Maura,169.0,17.0,Manuel Silvela
5,2022-01-01,50856526F_3861_2022-01-01T00:09:50,3861.0,1.0,0.48,"{'type': 'Point', 'coordinates': [-3.688822, 4...",NaN,2022-01-01T00:09:21,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688822, 4...",NaN,2022-01-01T00:09:50,73.0,21.0,Puerta del Ãngel CaÃ­do,73.0,21.0,Puerta del Ãngel CaÃ­do
7,2022-01-01,79006741Q_7657_2022-01-01T00:16:29,7657.0,1.0,6.62,"{'type': 'Point', 'coordinates': [-3.6653055, ...",NaN,2022-01-01T00:09:52,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6657777, ...",NaN,2022-01-01T00:16:29,192.0,22.0,MarquÃ©s de Zafra,190.0,17.0,Parque Roma

In [186]:
# aplicar la funcion de reemplazo de caracteres

for col in enero.select_dtypes(include=['object']).columns:
    enero[col] = replace_multiple(enero, col, replacements)

enero.head()

enero.shape

(244761, 19)

In [187]:
# eliminamos las columnas que tengan mas del 90% de valores nulos a traves de una funcion

def eliminar_nulos(df, porcentaje):
    for i in df:
        if df[i].isnull().sum() > (len(df) * porcentaje):
            df.drop(i, axis=1, inplace=True)
    return df

# llamada a la funcion

enero = eliminar_nulos(enero, 0.9)

enero.shape

(244761, 17)

In [188]:
enero.head()

,fecha,idTrip,idBike,fleet,trip_minutes,geolocation_unlock,unlock_date,locktype,unlocktype,geolocation_lock,lock_date,station_unlock,dock_unlock,unlock_station_name,station_lock,dock_lock,lock_station_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,489978239_1718_2022-01-01T00:18:37,1718.0,1.0,16.28,"{'type': 'Point', 'coordinates': [-3.6714166, ...",2022-01-01T00:02:20,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688398, 4...",2022-01-01T00:18:37,200.0,3.0,Avenida de los Toreros,64.0,4.0,Plaza de la Independencia
3,2022-01-01,06023769T_7340_2022-01-01T00:14:59,7340.0,1.0,7.10,"{'type': 'Point', 'coordinates': [-3.6894193, ...",2022-01-01T00:07:53,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6993465, ...",2022-01-01T00:14:59,69.0,5.0,Antonio Maura,169.0,17.0,Manuel Silvela
5,2022-01-01,50856526F_3861_2022-01-01T00:09:50,3861.0,1.0,0.48,"{'type': 'Point', 'coordinates': [-3.688822, 4...",2022-01-01T00:09:21,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.688822, 4...",2022-01-01T00:09:50,73.0,21.0,Puerta del Angel Caido,73.0,21.0,Puerta del Angel Caido
7,2022-01-01,79006741Q_7657_2022-01-01T00:16:29,7657.0,1.0,6.62,"{'type': 'Point', 'coordinates': [-3.6653055, ...",2022-01-01T00:09:52,STATION,STATION,"{'type': 'Point', 'coordinates': [-3.6657777, ...",2022-01-01T00:16:29,192.0,22.0,Marques de Zafra,190.0,17.0,Parque Roma

In [189]:
# eliminamos las columnas que no nos interesan fleet, locktype, unlocktype

enero.drop(['fleet', 'locktype', 'unlocktype'], axis=1, inplace=True)

enero.head()

,fecha,idTrip,idBike,trip_minutes,geolocation_unlock,unlock_date,geolocation_lock,lock_date,station_unlock,dock_unlock,unlock_station_name,station_lock,dock_lock,lock_station_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,489978239_1718_2022-01-01T00:18:37,1718.0,16.28,"{'type': 'Point', 'coordinates': [-3.6714166, ...",2022-01-01T00:02:20,"{'type': 'Point', 'coordinates': [-3.688398, 4...",2022-01-01T00:18:37,200.0,3.0,Avenida de los Toreros,64.0,4.0,Plaza de la Independencia
3,2022-01-01,06023769T_7340_2022-01-01T00:14:59,7340.0,7.10,"{'type': 'Point', 'coordinates': [-3.6894193, ...",2022-01-01T00:07:53,"{'type': 'Point', 'coordinates': [-3.6993465, ...",2022-01-01T00:14:59,69.0,5.0,Antonio Maura,169.0,17.0,Manuel Silvela
5,2022-01-01,50856526F_3861_2022-01-01T00:09:50,3861.0,0.48,"{'type': 'Point', 'coordinates': [-3.688822, 4...",2022-01-01T00:09:21,"{'type': 'Point', 'coordinates': [-3.688822, 4...",2022-01-01T00:09:50,73.0,21.0,Puerta del Angel Caido,73.0,21.0,Puerta del Angel Caido
7,2022-01-01,79006741Q_7657_2022-01-01T00:16:29,7657.0,6.62,"{'type': 'Point', 'coordinates': [-3.6653055, ...",2022-01-01T00:09:52,"{'type': 'Point', 'coordinates': [-3.6657777, ...",2022-01-01T00:16:29,192.0,22.0,Marques de Zafra,190.0,17.0,Parque Roma

In [190]:
# eliminamos los NaN del dataframe

enero.dropna(inplace=True)

enero.head()

,fecha,idTrip,idBike,trip_minutes,geolocation_unlock,unlock_date,geolocation_lock,lock_date,station_unlock,dock_unlock,unlock_station_name,station_lock,dock_lock,lock_station_name
1,2022-01-01,489978239_1718_2022-01-01T00:18:37,1718.0,16.28,"{'type': 'Point', 'coordinates': [-3.6714166, ...",2022-01-01T00:02:20,"{'type': 'Point', 'coordinates': [-3.688398, 4...",2022-01-01T00:18:37,200.0,3.0,Avenida de los Toreros,64.0,4.0,Plaza de la Independencia
3,2022-01-01,06023769T_7340_2022-01-01T00:14:59,7340.0,7.10,"{'type': 'Point', 'coordinates': [-3.6894193, ...",2022-01-01T00:07:53,"{'type': 'Point', 'coordinates': [-3.6993465, ...",2022-01-01T00:14:59,69.0,5.0,Antonio Maura,169.0,17.0,Manuel Silvela
5,2022-01-01,50856526F_3861_2022-01-01T00:09:50,3861.0,0.48,"{'type': 'Point', 'coordinates': [-3.688822, 4...",2022-01-01T00:09:21,"{'type': 'Point', 'coordinates': [-3.688822, 4...",2022-01-01T00:09:50,73.0,21.0,Puerta del Angel Caido,73.0,21.0,Puerta del Angel Caido
7,2022-01-01,79006741Q_7657_2022-01-01T00:16:29,7657.0,6.62,"{'type': 'Point', 'coordinates': [-3.6653055, ...",2022-01-01T00:09:52,"{'type': 'Point', 'coordinates': [-3.6657777, ...",2022-01-01T00:16:29,192.0,22.0,Marques de Zafra,190.0,17.0,Parque Roma
9,2022-01-01,76959007H_6653_2022-01-01T00:18:01,6653.0,8.07,"{'type': 'Point', 'coordinates': [-3.6983055, ...",2022-01-01T00:09:57,"{'type': 'Point', 'coordinates': [-3.7025024, ...",2022-01-01T00:18:01,183.0,3.0,Jaime el Conquistador,47.0,24.0,Jesus y Maria

In [195]:

with zipfile.ZipFile('trips_22_02_February-csv.zip', 'r') as zip_ref:
    zip_ref.extractall('trips_22_02_February-csv.zip')

# importar el archivo csv trips_22_01_January-csv

febrero = pd.read_csv('trips_22_02_February-csv.zip', sep=';', encoding='latin-1')

febrero.shape

FileNotFoundError: [Errno 2] No such file or directory: 'trips_22_02_February-csv.zip\\trips_22_02_February.csv'